name: newsapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cloud_firestore: ^3.4.5
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  firebase_auth: ^3.6.4
  firebase_core: ^1.21.0
  firebase_storage: ^10.3.6
  flutter:
    sdk: flutter
  get: 4.6.5
  google_fonts: ^3.0.1
  http: ^0.13.5
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  lottie: ^1.4.1
  url_launcher: ^6.1.5

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.0

flutter:
  uses-material-design: true
assets:
  - assets/images/56091-people-reading-news-on-phone.json
